import os
import sys
import time
import omegaconf.dictconfig
import torch
import copy
import pickle
import logging
import hydra
import pytorch_lightning as pl
from os import path as osp
from os import makedirs
from omegaconf import OmegaConf
from omegaconf.dictconfig import DictConfig
from pytorch_lightning.callbacks import ModelCheckpoint
from lightning_fabric.utilities.seed import seed_everything
from pytorch_lightning import loggers as pl_loggers
from torch.utils.data import DataLoader
from ..models.callbacks import EMAWeightUpdate, LogSample
from ..models.diffusion import DDPM, SuperResModel, UNetModel, Encoder
from ..models.autoencoders.GAE import GAE, GAE_PL
from ..models.joint_model import ModelWrapper
from main.util import configure_device, get_dataset, parse_str

logger = logging.getLogger(__name__)
logger.setLevel(logging.DEBUG)


@hydra.main(config_path='../configs', config_name='default_conf.yaml')
def train(config: DictConfig):
    # Get config
    logger.info(OmegaConf.to_yaml(config, resolve=True))
    config_joint = config.dataset.joint
    config_GAE = config.dataset.GAE

    # Set seed
    seed_everything(config_joint.training.seed, workers=True)

    # Dataset
    root = config_joint.data.root
    d_type = config_joint.data.name
    image_size = config_joint.data.image_size
    train_pattern = config_joint.training.train_pattern
    dataset = get_dataset(
        d_type, root, image_size, norm=config_joint.data.norm, flip=config_joint.data.hflip
    )
    # Todo change map location
    if train_pattern == 'encoder+GAE+ddpm':
        latent_z_mean_std = {}
        z_data = torch.load(config_GAE.data.root, map_location='cuda:0')
        latent_z_mean_std['mean'], latent_z_mean_std['std'] = z_data['mean'], z_data['std']
    else:
        latent_z_mean_std = None

    N = len(dataset)
    batch_size = config_joint.training.batch_size
    batch_size = min(N, batch_size)

    # Model
    lr = config_joint.training.training_lr
    weight_decay = config_joint.training.weight_decay

    # Model_ddpm
    attn_resolutions = parse_str(config_joint.model_ddpm.attn_resolutions)
    dim_mults = parse_str(config_joint.model_ddpm.dim_mults)
    ddpm_type = config_joint.training.type

    # superres model for conditinal training
    decoder_cls = UNetModel
    decoder = decoder_cls(
        in_channels=config_joint.data.n_channels,
        model_channels=config_joint.model_ddpm.dim,
        out_channels=3,
        emb_channels=config_joint.model_ddpm.emb_channels,  # t_emb and z_emb(generated by AE)
        num_res_blocks=config_joint.model_ddpm.n_residual,
        attention_resolutions=attn_resolutions,
        channel_mult=dim_mults,
        use_checkpoint=False,
        dropout=config_joint.model_ddpm.dropout,
        num_heads=config_joint.model_ddpm.n_heads,
        z_dim=config_joint.training.z_dim,
        use_scale_shift_norm=config_joint.model_ddpm.use_scale_shift_norm,
        use_z=config_joint.model_ddpm.use_z,
        use_x_hat=config_joint.model_ddpm.use_x_hat,
        use_mappingnet=config_joint.model_ddpm.use_mappingnet
    )

    # EMA settings
    ema_decoder = copy.deepcopy(decoder)
    for p in ema_decoder.parameters():
        p.requires_grad = False

    # Encoder settings
    config_model_encoder = config_joint.model_Encoder
    attention_resolutions = parse_str(config_model_encoder.attention_resolutions)
    channel_mult = parse_str(config_model_encoder.channel_mult)
    encoder = Encoder(
        in_channels=config_model_encoder.in_channels,
        model_channels=config_model_encoder.model_channels,
        out_channels=config_model_encoder.out_channels,
        num_res_blocks=config_model_encoder.num_res_blocks,
        attention_resolutions=attention_resolutions,
        dropout=config_model_encoder.dropout,
        channel_mult=channel_mult,
        conv_resample=config_model_encoder.conv_resample,
        use_checkpoint=config_model_encoder.use_checkpoint,
        num_heads=config_model_encoder.num_heads,
        resblock_updown=config_model_encoder.resblock_updown
    )
    # base_sampler setting
    ddpm_cls = DDPM
    online_ddpm = ddpm_cls(
        decoder,
        beta_1=config_joint.model_ddpm.beta1,
        beta_2=config_joint.model_ddpm.beta2,
        T=config_joint.model_ddpm.n_timesteps,
        var_type=config_joint.model_ddpm.var_type,
    )
    target_ddpm = ddpm_cls(
        ema_decoder,
        beta_1=config_joint.model_ddpm.beta1,
        beta_2=config_joint.model_ddpm.beta2,
        T=config_joint.model_ddpm.n_timesteps,
        var_type=config_joint.model_ddpm.var_type,
    )

    assert isinstance(online_ddpm, ddpm_cls)
    assert isinstance(target_ddpm, ddpm_cls)
    logger.info(f"Using DDPM with type: {ddpm_cls} and data norm: {config_joint.data.norm}")

    # GAE settings
    if train_pattern == 'encoder+GAE+ddpm':
        # gae_pl_ckpt = torch.load(config_joint.training.Gae_chkpt_path, map_location='cpu')
        # state_dict = gae_pl_ckpt['state_dict']
        # new_state_dict = OrderedDict()
        # for key in state_dict.keys():
        #     new_state_dict['Gae_pl' + key] = state_dict[key]
        Gae_pl = GAE_PL.load_from_checkpoint(config_joint.training.Gae_chkpt_path, strict=False, config=config_GAE)
        # for key in Gae_pl.state_dict().keys():
        #     logger.debug(key)
    else:
        Gae_pl = None

    # Trainer
    train_kwargs = {}
    results_dir = config_joint.training.results_dir

    # logger setting
    logdir_path = osp.join(results_dir, 'checkpoints', f'{config_joint.training.training_name}--checkpoints')
    tb_looger = pl_loggers.TensorBoardLogger(save_dir=logdir_path,
                                             name='Tensorboard_logs',
                                             version=config_joint.training.training_name + '_' + \
                                                     time.strftime('%Y-%m-%d--%H_%M_%S')
                                             )
    tb_looger.log_hyperparams(OmegaConf.to_container(config_joint, resolve=True))
    train_kwargs['logger'] = tb_looger

    # Setting for storage_path for sample in training
    storage_path = osp.join(logdir_path, f'{d_type}-Samples_in_training')
    sample_storage_path = storage_path if config_joint.training.sample_storage_path == "" else config_joint.training.sample_storage_path
    if not osp.exists(sample_storage_path):
        os.makedirs(sample_storage_path, exist_ok=True)

    # joint_model init
    if train_pattern == 'encoder+ddpm':
        model_wrapper = ModelWrapper(
            online_ddpm,
            target_ddpm,
            encoder,
            Gae_pl=None,
            config=config_joint,
            lr=lr,
            lr_scheduler=config_joint.training.lr_scheduler,
            training_steps=config_joint.training.steps,
            weight_decay=weight_decay,
            cfd_rate=config_joint.training.cfd_rate,
            loss=config_joint.training.loss,
            conditional=False if ddpm_type == "uncond" else True,
            grad_clip_val=config_joint.training.grad_clip,
            use_z=config_joint.training.use_z,
            loss_weight=config_joint.training.gamma,
            train_pattern=train_pattern,
            sample_storage_path=sample_storage_path,
            sample_from=config_joint.training.sample_from,
            resample_strategy=config_joint.training.resample_strategy,
            skip_strategy=config_joint.training.skip_strategy,
            sample_method=config_joint.training.sample_method,
            pred_steps=config_joint.training.pred_steps,
            is_group_training=config_joint.training.is_group_training,
        )
    else:
        # state_dict = torch.load(config_joint.training.diffae_chkpt_path, map_location='cpu')['state_dict']
        # original_model = ModelWrapper.load_from_checkpoint(config_joint.training.diffae_chkpt_path, strict=True)
        # online_ddpm, target_ddpm, encoder = original_model.online_ddpm, original_model.target_ddpm, original_model.encoder
        model_wrapper = ModelWrapper.load_from_checkpoint(
            config_joint.training.diffae_chkpt_path,
            strict=False,
            online_network=online_ddpm,
            target_network=target_ddpm,
            encoder=encoder,
            Gae_pl=Gae_pl,
            config=config_joint,
            lr=lr,
            lr_scheduler=config_joint.training.lr_scheduler,
            training_steps=config_joint.training.steps,
            weight_decay=weight_decay,
            cfd_rate=config_joint.training.cfd_rate,
            loss=config_joint.training.loss,
            conditional=False if ddpm_type == "uncond" else True,
            grad_clip_val=config_joint.training.grad_clip,
            use_z=config_joint.training.use_z,
            loss_weight=config_joint.training.gamma,
            train_pattern=train_pattern,
            sample_storage_path=sample_storage_path,
            sample_from=config_joint.training.sample_from,
            resample_strategy=config_joint.training.resample_strategy,
            skip_strategy=config_joint.training.skip_strategy,
            sample_method=config_joint.training.sample_method,
            pred_steps=config_joint.training.pred_steps,
            is_group_training=config_joint.training.is_group_training,
            latent_z_mean_std=latent_z_mean_std,
            group_size=config_joint.data.group_size,
            batch_size=config_joint.training.batch_size,
        )
        # model_wrapper = ModelWrapper(
        #     online_network=online_ddpm,
        #     target_network=target_ddpm,
        #     encoder=encoder,
        #     Gae_pl=Gae_pl,
        #     lr=lr,
        #     lr_scheduler=config_joint.training.lr_scheduler,
        #     training_steps=config_joint.training.steps,
        #     weight_decay=weight_decay,
        #     cfd_rate=config_joint.training.cfd_rate,
        #     loss=config_joint.training.loss,
        #     conditional=False if ddpm_type == "uncond" else True,
        #     grad_clip_val=config_joint.training.grad_clip,
        #     use_z=config_joint.training.use_z,
        #     loss_weight=config_joint.training.gamma,
        #     train_pattern=train_pattern,
        #     sample_storage_path=sample_storage_path,
        #     sample_from=config_joint.training.sample_from,
        #     resample_strategy=config_joint.training.resample_strategy,
        #     skip_strategy=config_joint.training.skip_strategy,
        #     sample_method=config_joint.training.sample_method,
        #     pred_steps=config_joint.training.pred_steps,
        #     is_group_training=config_joint.training.is_group_training,
        #     latent_z_mean_std=latent_z_mean_std,
        #     group_size=config_joint.data.group_size,
        #     batch_size=config_joint.training.batch_size,
        # )

    # Setup callbacks
    checkpoint_path = os.path.join(logdir_path, 'Model_weights')
    if not osp.exists(checkpoint_path):
        makedirs(checkpoint_path)
    chkpt_callback = ModelCheckpoint(
        monitor="whole_loss",
        save_top_k=1,
        save_last=True,
        dirpath=checkpoint_path,
        filename=f"model_{train_pattern}-{config_joint.training.chkpt_prefix}" + "-{epoch:04d}-{global_step:09d}-{whole_loss:.6f}",
        every_n_train_steps=config_joint.training.chkpt_interval,
    )
    sample_log = LogSample(num_samples=config_joint.training.num_samples,
                           sample_every_step=config_joint.training.sample_every_step,
                           storage_path=sample_storage_path,
                           )
    train_kwargs["default_root_dir"] = results_dir
    train_kwargs["max_epochs"] = config_joint.training.epochs
    # train_kwargs["max_steps"] = config_joint.training.steps
    train_kwargs["log_every_n_steps"] = config_joint.training.log_step
    train_kwargs["callbacks"] = [chkpt_callback, sample_log]

    if config_joint.training.use_ema:
        ema_callback = EMAWeightUpdate(tau=config_joint.training.ema_decay)
        train_kwargs["callbacks"].append(ema_callback)

    device = config_joint.training.device
    loader_kws = {}
    if device.startswith("gpu"):
        _, devs = configure_device(device)
        train_kwargs['accelerator'] = 'gpu'
        train_kwargs["devices"] = devs

        if len(devs) > 1:
            # Disable find_unused_parameters when using DDP training for performance reasons
            from pytorch_lightning.plugins import DDPPlugin
            train_kwargs["accelerator"] = "ddp"
            train_kwargs["plugins"] = DDPPlugin(find_unused_parameters=False)

        loader_kws["persistent_workers"] = True
    else:
        raise NotImplementedError()

    # Half precision training
    if config_joint.training.fp16:
        train_kwargs["precision"] = 16

    # Loader
    loader = DataLoader(
        dataset,
        batch_size,
        num_workers=config_joint.training.workers,
        pin_memory=False,
        shuffle=True,
        drop_last=True,
        **loader_kws,
    )
    train_kwargs['fast_dev_run'] = False
    trainer = pl.Trainer(**train_kwargs)
    logger.info(f"Running Trainer with kwargs: {train_kwargs}")
    # restore from checkpoint
    restore_path = config_joint.training.restore_path
    if restore_path != "":
        # Restore checkpoint
        train_kwargs["resume_from_checkpoint"] = restore_path
        logger.info(f'Training from {restore_path}')
    elif osp.exists(osp.join(logdir_path, 'Model_weights', 'last.ckpt')):
        train_kwargs["resume_from_checkpoint"] = osp.join(logdir_path, 'Model_weights', 'last.ckpt')
        logger.info(f"Training from {osp.join(logdir_path, 'Model_weights', 'last.ckpt')}")
    else:
        train_kwargs["resume_from_checkpoint"] = None
        logger.info('A fresh start')

    trainer.fit(model_wrapper, train_dataloaders=loader, ckpt_path=train_kwargs['resume_from_checkpoint'])


if __name__ == "__main__":
    train()
