import os
import sys
import time
import torch
import copy
import logging
import hydra
import pytorch_lightning as pl
from os import path as osp
from os import makedirs
from omegaconf import OmegaConf
from pytorch_lightning.callbacks import ModelCheckpoint
from lightning_fabric.utilities.seed import seed_everything
from pytorch_lightning import loggers as pl_loggers
from torch.utils.data import DataLoader
from ..models.callbacks import LogSample
from ..models.diffusion import DDPM, SuperResModel, Encoder
from ..models.autoencoders.GAE import GAE_PL
from ..models.joint_model import ModelWrapper
from main.util import configure_device, get_dataset, parse_str

logger = logging.getLogger(__name__)
logger.setLevel(logging.INFO)


@hydra.main(config_path='../configs', config_name='default_conf.yaml')
def train_gae(config):
    # Get config
    config_GAE = config.dataset.GAE
    config_joint = config.dataset.joint

    logger.info(OmegaConf.to_yaml(config_GAE, resolve=True))

    # Set seed
    seed_everything(config_GAE.training.seed, workers=True)

    # Dataset
    root = config_GAE.data.root
    d_type = '_'.join(config_GAE.data.name.split('_')[:3]) + '_z'

    image_size = config_GAE.data.image_size
    dsize = config_GAE.data.dataset_size
    dataset = get_dataset(
        d_type, root, image_size, norm=config_GAE.data.norm, flip=False
    )
    N = len(dataset)
    batch_size = config_GAE.training.batch_size
    batch_size = min(N, batch_size)

    # Model
    # GAE setting
    GAE_pl = GAE_PL(config_GAE)
    # Sampler settings
    attn_resolutions = parse_str(config_joint.model_ddpm.attn_resolutions)
    dim_mults = parse_str(config_joint.model_ddpm.dim_mults)
    ddpm_type = config_joint.training.type
    decoder = SuperResModel(
        in_channels=config_joint.data.n_channels,
        model_channels=config_joint.model_ddpm.dim,
        out_channels=3,
        emb_channels=config_joint.model_ddpm.emb_channels,  # t_emb and z_emb(generated by AE)
        num_res_blocks=config_joint.model_ddpm.n_residual,
        attention_resolutions=attn_resolutions,
        channel_mult=dim_mults,
        use_checkpoint=False,
        dropout=config_joint.model_ddpm.dropout,
        num_heads=config_joint.model_ddpm.n_heads,
        z_dim=config_joint.training.z_dim,
        use_scale_shift_norm=config_joint.model_ddpm.use_scale_shift_norm,
        use_z=config_joint.model_ddpm.use_z,
        use_x_hat=config_joint.model_ddpm.use_x_hat,
        use_mappingnet=config_joint.model_ddpm.use_mappingnet
    )
    ema_decoder = copy.deepcopy(decoder)
    for p in ema_decoder.parameters():
        p.requires_grad = False

    # Encoder settings
    config_model_encoder = config_joint.model_Encoder
    attention_resolutions = parse_str(config_model_encoder.attention_resolutions)
    channel_mult = parse_str(config_model_encoder.channel_mult)
    encoder = Encoder(
        in_channels=config_model_encoder.in_channels,
        model_channels=config_model_encoder.model_channels,
        out_channels=config_model_encoder.out_channels,
        num_res_blocks=config_model_encoder.num_res_blocks,
        attention_resolutions=attention_resolutions,
        dropout=config_model_encoder.dropout,
        channel_mult=channel_mult,
        conv_resample=config_model_encoder.conv_resample,
        use_checkpoint=config_model_encoder.use_checkpoint,
        num_heads=config_model_encoder.num_heads,
        resblock_updown=config_model_encoder.resblock_updown
    )
    # base_sampler setting
    ddpm_cls = DDPM
    online_ddpm = ddpm_cls(
        decoder,
        beta_1=config_joint.model_ddpm.beta1,
        beta_2=config_joint.model_ddpm.beta2,
        T=config_joint.model_ddpm.n_timesteps,
        var_type=config_joint.model_ddpm.var_type,
    )
    target_ddpm = ddpm_cls(
        ema_decoder,
        beta_1=config_joint.model_ddpm.beta1,
        beta_2=config_joint.model_ddpm.beta2,
        T=config_joint.model_ddpm.n_timesteps,
        var_type=config_joint.model_ddpm.var_type,
    )

    joint_model = ModelWrapper.load_from_checkpoint(
        config_GAE.model.diffusion_ckpt_path,
        strict=True,
        online_network=online_ddpm,
        target_network=target_ddpm,
        encoder=encoder,
    )
    sampler = joint_model.spaced_diffusion

    # Trainer
    train_kwargs = {}
    results_dir = config_GAE.training.results_dir

    # logger setting
    logdir_path = osp.join(results_dir, 'checkpoints', f'{config_GAE.training.training_name}--checkpoints')
    tb_looger = pl_loggers.TensorBoardLogger(save_dir=logdir_path,
                                             name='Tensorboard_logs',
                                             version=config_GAE.training.training_name + \
                                                     time.strftime('%Y-%m-%d--%H_%M_%S')
                                             ) 
    tb_looger.log_hyperparams(OmegaConf.to_container(config_GAE, resolve=True))
    train_kwargs['logger'] = tb_looger

    # Setting for storage_path for sample in training
    storage_path = osp.join(logdir_path, f'{d_type}-Samples_in_training')
    sample_storage_path = storage_path if config_GAE.training.sample_storage_path == "" else config_GAE.training.sample_storage_path
    if not osp.exists(sample_storage_path):
        os.makedirs(sample_storage_path, exist_ok=True)
    GAE_pl.sampler = sampler
    if config_GAE.data.norm:
        GAE_pl.z_mean, GAE_pl.z_std = dataset.z_mean, dataset.z_std
    GAE_pl.sample_storage_path = sample_storage_path
    GAE_pl.sample_from = joint_model.sample_from

    # Setup callbacks
    checkpoint_path = os.path.join(logdir_path, 'Model_weights')
    if not osp.exists(checkpoint_path):
        makedirs(checkpoint_path)
    chkpt_callback = ModelCheckpoint(
        monitor='whole_loss',
        save_top_k=1,
        save_last=True,
        dirpath=checkpoint_path,
        filename=f"model_GAE-{config_GAE.training.chkpt_prefix}" + "-{epoch:04d}-{global_step:06d}-{whole_loss:.6f}",
        every_n_epochs=config_GAE.training.chkpt_interval,
        save_on_train_epoch_end=True,
    )
    sample_log = LogSample(num_samples=config_GAE.training.num_samples,
                           sample_every_step=config_GAE.training.sample_every_step,
                           storage_path=sample_storage_path,
                           )
    train_kwargs["default_root_dir"] = results_dir
    train_kwargs["max_epochs"] = config_GAE.training.epochs
    train_kwargs["log_every_n_steps"] = config_GAE.training.log_step
    train_kwargs["callbacks"] = [chkpt_callback, sample_log]

    device = config_GAE.training.device
    loader_kws = {}
    if device.startswith("gpu"):
        _, devs = configure_device(device)
        train_kwargs['accelerator'] = 'gpu'
        train_kwargs["devices"] = devs

        if len(devs) > 1:
            # Disable find_unused_parameters when using DDP training for performance reasons
            from pytorch_lightning.plugins import DDPPlugin
            train_kwargs["accelerator"] = "ddp"
            train_kwargs["plugins"] = DDPPlugin(find_unused_parameters=False)

        loader_kws["persistent_workers"] = True
    elif device == "tpu":
        train_kwargs["tpu_cores"] = 8

    # Half precision training
    if config_GAE.training.fp16:
        train_kwargs["precision"] = 16

    # Loader
    loader = DataLoader(
        dataset,
        batch_size,
        num_workers=config_GAE.training.workers,
        pin_memory=True,
        shuffle=True,
        drop_last=True,
        prefetch_factor=20,
        **loader_kws,
    )

    logger.info(f"Running Trainer with kwargs: {train_kwargs}")
    trainer = pl.Trainer(**train_kwargs)

    # restore from checkpoint
    restore_path = config_GAE.training.restore_path
    if restore_path != "":
        # Restore checkpoint
        train_kwargs["resume_from_checkpoint"] = restore_path
        logger.info(f'Training from {restore_path}')
    elif osp.exists(osp.join(logdir_path, 'Model_weights', 'last.ckpt')):
        train_kwargs["resume_from_checkpoint"] = osp.join(logdir_path, 'Model_weights', 'last.ckpt')
        logger.info(f"Training from {osp.join(logdir_path, 'Model_weights', 'last.ckpt')}")
    else:
        train_kwargs["resume_from_checkpoint"] = None
        logger.info('A fresh start')
    trainer.fit(GAE_pl, train_dataloaders=loader, ckpt_path=train_kwargs['resume_from_checkpoint'])


if __name__ == "__main__":
    train_gae()