# for joint training
joint:
  data:
    root: "/home/lyp/Data/Fonts/fonts_128.lmdb"
    name: "fonts_128"
    is_group_dataset: False
    group_size: 6
    image_size: 128
    hflip: True
    n_channels: 3
    norm: True

  model_ddpm:
    dim: 128
    emb_channels: 512 # should be same as encoder_out_channels
    attn_resolutions: "16,"
    n_residual: 2
    dim_mults: "1,1,2,3,4"
    dropout: 0.1
    n_heads: 1
    beta1: 1e-4
    beta2: 0.02
    use_scale_shift_norm: True
    n_timesteps: 1000
    var_type: fixedlarge
    use_z: True
    z_dim: ${dataset.joint.model_Encoder.out_channels}
    use_x_hat: False
    resblock_updown: True
    use_mappingnet: False

  model_Encoder:
    in_channels: 3
    model_channels: ${dataset.joint.model_ddpm.dim}
    out_channels: 512 # latent-code length 恒为512
    num_res_blocks: 2
    attention_resolutions: "16,"
    dropout: 0.1
    channel_mult: "1,1,2,3,4,4"
    conv_resample: True
    use_checkpoint: False
    num_heads: 1
    resblock_updown: True

  training:
    seed: 42
    is_group_training: ${dataset.joint.data.is_group_dataset}
    training_name: "fonts_128_diffae_form1"
    fp16: False
    use_ema: True
    use_z: ${dataset.joint.model_ddpm.use_z}
    z_dim: ${dataset.joint.model_Encoder.out_channels}
    type: 'form1'
    ema_decay: 0.99
    batch_size: 36
    epochs: 250
    steps: 6_000_000
    log_step: 1
    device: "gpu:0"
    chkpt_interval: 1010
    optimizer: "Adam"
    training_lr: 2e-5
    weight_decay: 0
    beta_1: 0.9
    beta_2: 0.999
    restore_path: ""
    results_dir: "/home/lyp/Code/DiffuseGAE"
    workers: 128
    grad_clip: 1.0
    lr_scheduler: 'warmup'
    warmup: 0
    loss: "l2"
    chkpt_prefix: ""
    cfd_rate: 0.0
    train_pattern: 'encoder+ddpm'
    lambda_combine: 0.5 # loss_Gae weight
    lambda_unsup: 0.5 # loss_Gae weight
    gamma: 0. # loss weight
    Gae_chkpt_path: '' # path /home/lyp/Code/Group-Supervised-Learning/checkpoints/pretrained_models/fonts.ckpt
    # log samples paras
    sample_every_step: 1000
    num_samples: 24
    sample_storage_path: ""
    samples_norm: False
    sample_from: 'target'
    resample_strategy: 'spaced'
    skip_strategy: 'uniform'
    sample_method: 'ddim'
    pred_steps: 20

# for GAE training
GAE:
  data:
    root: "/home/lyp/Data/ilab/ilab_128.lmdb"
    name: "ilab_128"
    is_group_dataset: False
    group_size: 4
    image_size: 128
    hflip: True
    n_channels: 3
    norm: True
  model:
    in_channels: ${dataset.joint.model_Encoder.out_channels}
    base_dim: 512
    num_skip_blocks: 4
    out_channels: ${dataset.joint.model_Encoder.out_channels}
    repeat_num: 2
    dropout: 0.1
    z_dim: 100
    z_id_dim: 60
    z_back_dim: 20
    z_pose_dim: 20
  training:
    seed: 42
    is_group_training: ${dataset.joint.data.is_group_dataset}
    training_name: "ilab_128-diffae-form1"
    fp16: True
    use_ema: True
    use_z: ${dataset.joint.model_ddpm.use_z}
    z_dim: ${dataset.joint.model_Encoder.out_channels}
    type: 'form1'
    ema_decay: 0.99
    batch_size: 60
    epochs: 10
    steps: 160_000
    log_step: 1
    device: "gpu:0"
    chkpt_interval: 1010
    optimizer: "Adam"
    training_lr: 4e-5
    weight_decay: 0
    beta_1: 0.9
    beta_2: 0.999
    restore_path: ""
    results_dir: "/home/lyp/Code/DiffuseGAE"
    workers: 32
    grad_clip: 1.0
    lr_scheduler: 'warmup'
    warmup: 0
    loss: "l2"
    chkpt_prefix: ""
    cfd_rate: 0.0
    train_pattern: 'encoder+ddpm'
    lambda_combine: 0.5 # loss_Gae weight
    lambda_unsup: 0.5 # loss_Gae weight
    gamma: 0 # loss weight # only > 0 in encoder+decoder+ddpm pattern and GAE training
    Gae_chkpt_path: "" # leave it "" when you don't want to load GAE pre-trained weights
    # '/home/lyp/Code/Group-Supervised-Learning/checkpoints/pretrained_models/ilab_20M.ckpt'
    sample_every_step: 1000
    num_samples: 24
    sample_storage_path: ""
    samples_norm: False
    sample_from: 'target'
    resample_strategy: 'spaced'
    skip_strategy: 'uniform'
    sample_method: 'ddim'
    pred_steps: 50

